updated controller/application file to add devise
kayjeee/Hi-Blog_app_kayjeee pull request #11
Opened 2023-09-20 14:22 UTC by kayjeee

# Pull Request: Devise Installation and Configuration

## Description

This pull request addresses the implementation of user authentication and registration using Devise in our Rails application. The key features added include user registration, login using email and password, secure storage of hashed passwords in the database, email confirmation, and password reset. Additionally, the views for registration and login have been customized to match the wireframes provided in the Sneak Peek.

## Changes Made

- Removed the custom `current_user` method from `ApplicationController` as Devise provides a built-in method for this purpose.

### Devise Setup and Features

- Installed and configured Devise in the project.
- Implemented user registration functionality.
- Enabled users to log in using their email and password.
- Securely stored hashed passwords in the database.
- Introduced email confirmation for user accounts.
- Implemented password reset functionality.

### UI Improvements

- Modified the default Devise views for registration and login to align with the wireframes from the Sneak Peek. This enhances the user experience and ensures a consistent look and feel.

## Checklist

- [x] Installed and configured Devise for user authentication.
- [x] Implemented user registration.
- [x] Enabled user login using email and password.
- [x] Stored hashed passwords securely in the database.
- [x] Added email confirmation for user accounts.
- [x] Implemented password reset functionality.
- [x] Customized registration and login views to match wireframes.
- [x] Thoroughly tested all added features.

I am working solo on this project, as indicated by this screenshot:
![Solo Work](https://drive.google.com/uc?id=1Gnt7mwJ8eBN5TD93_nVY9_dZl5LuE--z)

Please review and merge this pull request to integrate the changes related to Devise installation, authentication, and the improved user interface.

2023-09-20 15:19 UTC, DeliceLydia requested changes
### Hi @kayjeee, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Followed gitflow


## Required Changes ♻️
_Check the comments under the review._



### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 15:19 UTC, DeliceLydia commented on app/controllers/application_controller.rb
>  end
- [ ] I can see you removed `current user` in this file to be able to use `devise` but make sure the user `model` allows the registration of a new user, hashing a password in the database, asking for confirmation email etc.
	
```
devise :database_authenticatable, :registerable,
	    :recoverable, :rememberable, :validatable, :confirmable
				
```
Make sure you follow this [getting started link](https://github.com/heartcombo/devise)

2023-09-20 17:38 UTC, kayjeee commented on app/controllers/application_controller.rb
>  end
done

2023-09-20 18:50 UTC, aamirkhan2478 requested changes
Hi @kayjeee, 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 18:50 UTC, aamirkhan2478 commented on app/models/user.rb
- [ ] As mentioned by the previous reviewer :point_up: please add the devise properly still your devise is not configured properly follow all my all steps below :point_down: to configure devise properly :slightly_smiling_face: 


1. Add Devise to your Gemfile and install it using Bundler:

   ```ruby
   gem 'devise'
   ```

   Run the following command to install the gem:

   ```bash
   bundle install
   ```

2. After installing Devise, you need to generate the Devise configuration files and the User model by running the following command:

   ```bash
   rails generate devise:install
   ```
3. At this point, a number of instructions will appear in the console. Among these instructions, you'll need to set up the default URL options for the Devise mailer in each environment. Here is a possible configuration for `config/environments/development.rb`:
```ruby
config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
```

4. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

```ruby
       root to: "home#index"
```

5. Generate a Devise model (usually for users) with the necessary fields. 

   ```bash
   rails generate devise User
   ```

This will create a migration file for the User model and the necessary configuration in your `config/routes.rb` file.

6. Uncommented from line no. 25 to 28 inside `migrate/add_devise_to_users.rb` and then migrate it after that you will see your users table is updated with some new fields 


7. Customize your User model as needed in `app/models/user.rb`. Devise provides a variety of authentication-related methods and options that you can configure to suit your application's requirements.

```ruby
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
```

8. In your application layout file (usually `app/views/layouts/application.html.erb`), add the following line to display flash messages, which Devise uses to communicate with users:

   ```erb
   <%= flash[:notice] %>
   <%= flash[:alert] %>
   ```

9. Customize the views provided by Devise if needed. You can generate the default views to customize by running:

   ```bash
   rails generate devise:views
   ```

 This will create the Devise view files in the `app/views/devise` directory, which you can edit to match your application's styling.

10. Configure Devise routes in `config/routes.rb`. Devise has a variety of routes you can use. For example, to set up routes for registration and session management, add the following lines:

   ```ruby
   devise_for :users
   ```

11. Restart your Rails server to apply the changes.

Consider the [Devise documentation](https://github.com/heartcombo/devise#getting-started) for more advanced configuration options and security considerations, such as setting up solid parameters and customizing authentication views and controllers.

If you still facing some problems then watch this [YouTube video](https://www.youtube.com/watch?v=44sA_j2iL-Q&ab_channel=DavidBattersby)

2023-09-21 08:04 UTC, afanimartin approved these changes
Hi @kayjeee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Devise installed and configured with the User model as requested

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 11:13 UTC, merged